CREATE TABLE REVIEW(
	REVIEW_PK INT PRIMARY KEY,
	ACCOUNT_PK INT, --FK
	ITEM_PK INT, --FK
	REVIEW_TITLE VARCHAR(50),
	REVIEW_CONTENT VARCHAR(2000),
	REVIEW_DATE DATE DEFAULT SYSDATE,
	REVIEW_STAR NUMBER(1) DEFAULT 0,

	CONSTRAINT FK_ACCOUNT_REVIEW FOREIGN KEY (ACCOUNT_PK) REFERENCES ACCOUNT(ACCOUNT_PK),
	CONSTRAINT FK_ITEM_REVIEW FOREIGN KEY (ITEM_PK) REFERENCES ITEM(ITEM_PK)
);
--리뷰PK,회원PK,상품PK,리뷰제목,리뷰내용,리뷰날자,리뷰 별점
--FK 연결하고 명시적 선언

DROP TABLE REVIEW;
-- 테이블 드랍
DROP TABLE REVIEW CASCADE CONSTRAINTS;
-- 강제 테이블 드랍


--필요한거
--상품별리뷰
--내가쓴 리뷰 확인
--리뷰작성
--리뷰수정
--리뷰 모두삭제
--리뷰 하나만 삭제

--리뷰PK 자동증가용 시퀀스 사용
CREATE SEQUENCE REVIEW_SEQ
START WITH 6000
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 시퀀스 삭제
DROP SEQUENCE REVIEW_SEQ;

-- 리뷰작성
INSERT INTO REVIEW (REVIEW_PK,ACCOUNT_PK,ITEM_PK,REVIEW_TITLE,
	REVIEW_CONTENT,REVIEW_STAR
) VALUES(
	REVIEW_SEQ.NEXTVAL, '2','1','리뷰제목','리뷰내용','5'
);

INSERT INTO REVIEW (REVIEW_PK,ACCOUNT_PK,ITEM_PK,REVIEW_TITLE,
	REVIEW_CONTENT,REVIEW_STAR
) VALUES(
	REVIEW_SEQ.NEXTVAL, '2','2','리뷰제목','리뷰내용','5'
);

--상품별리뷰 -> 페이지네이션 사용
--SELECT 1 ->리뷰PK,아이템PK,리뷰제목,리뷰내용,별점 가져오기
--SELECT 2 ->리뷰테이블 안에 있는 리뷰PK,아이템PK,리뷰제목,리뷰내용,별점 가져오기
--ROW_NUMBER() : 조회된 리뷰 하나하나에 번호 붙이기
--OREDR BY REVIEW_PK DESC
--최신리뷰가 1번이 되도록 설정
--특정 상품의 리뷰만 조회

SELECT 
    REVIEW_PK,
    ITEM_PK,
    REVIEW_TITLE,
    REVIEW_CONTENT,
    REVIEW_STAR
FROM (
    SELECT 
        R.REVIEW_PK,
       	R.ITEM_PK,
        R.REVIEW_TITLE,
        R.REVIEW_CONTENT,
        R.REVIEW_STAR,
        ROW_NUMBER() OVER (
            ORDER BY R.REVIEW_PK DESC
        ) AS RN
    FROM REVIEW R
    WHERE ITEM_PK ='1'
)
WHERE RN BETWEEN 5 AND 5;

--리뷰 존재여부 확인
SELECT COUNT(*)FROM REVIEW 
WHERE ACCOUNT_PK = '2'
  AND ITEM_PK = '1';

--내가쓴 리뷰 확인
SELECT REVIEW_PK,ITEM_PK,ACCOUNT_PK,REVIEW_TITLE,REVIEW_CONTENT,REVIEW_STAR
FROM REVIEW WHERE ACCOUNT_PK = '2';

--상품별 전체 리뷰 개수
SELECT COUNT(*) FROM WHERE ITEM_PK ='1';

--리뷰수정페이지 데이터조회(리뷰수정화면 전용) -> 어카운트 조인필요
--어떤리뷰 수정할건지 내가쓴 리뷰가 맞는지 내이름 화면에 표시하기
SELECT
	R.REVIEW_PK,
	A.ACCOUNT_NAME,
	R.REVIEW_TITLE,
	R.REVIEW_STAR,
	R.REVIEW_CONTENT
FROM REVIEW R
JOIN ACCOUNT A
	ON R.ACCOUNT_PK = A.ACCOUNT_PK
	WHERE R.REVIEW_PK ='3'
	AND R.ACCOUNT_PK = '2';


--상품별 별점 목록
SELECT REVIEW_STAR FROM REVIEW WHERE ITEM_PK ='1';



--리뷰수정
UPDATE REVIEW
SET
    REVIEW_TITLE   = '수정된 제목',
    REVIEW_CONTENT = '수정된 내용',
    REVIEW_STAR    = '4'
WHERE REVIEW_PK = '3'
  AND ACCOUNT_PK = '2'
  AND ITEM_PK='1';

--내가쓴 모든리뷰삭제
DELETE FROM REVIEW WHERE ACCOUNT_PK = '2'; 

--내가쓴리뷰 하나만삭제
DELETE FROM REVIEW
WHERE REVIEW_PK = '3'
AND ACCOUNT_PK = '2';

--확인용
SELECT*FROM REVIEW;


/*



--리뷰작성 인서트 체크용
INSERT INTO ITEM(
	ITEM_PK,ITEM_NAME
)VALUES('1','전구'
);

INSERT INTO ITEM(
	ITEM_PK,ITEM_NAME
)VALUES('2','트리'
);
*/

